import Foundation
import CryptoKit
import Capacitor

// Signed OTA content channel (Phase 1B of docs/app-remediation-plan.md).
//
// The app ships a bundled snapshot of the site. This updater lets a crisis-number
// fix merged to main reach installed apps WITHOUT an App Store release — and lets
// nothing else in. The chain of custody:
//
//   1. The site build emits /ota/manifest.json (sha256 of every content file)
//      and manifest.sig, an ed25519 signature over the manifest's exact bytes,
//      made with a private key held as a deploy secret. (site/tools/gen-ota-manifest.mjs)
//   2. On launch the app fetches both, and verifies the signature against the
//      PUBLIC key compiled into this file. An unsigned or tampered manifest is
//      refused outright — the app then simply keeps serving what it has.
//   3. Files whose hash differs from the active content are downloaded from the
//      site (a static host: every manifest path is a real URL), each verified
//      against its sha256 FROM THE SIGNED MANIFEST before being kept.
//   4. A complete new content root is STAGED next to the active one (unchanged
//      files are hard-linked, so disk cost is only the delta), then activated
//      atomically by a pointer file.
//   5. Activation happens on the NEXT launch — never mid-session, so a page is
//      never yanked out from under someone reading it. WikiBridgeViewController
//      asks activeContentRoot() for the serving root before the webview loads.
//   6. Rollback: the previous root is kept. If the current root fails its
//      launch-time validation, the app falls back previous → bundle. The bundle
//      is never deleted — there is always a last-known-good.
//
// A NEW BINARY always wins: if the bundle is newer than the OTA content (an App
// Store update shipped), all OTA state is discarded. This mirrors Capacitor's own
// isNewBinary handling and prevents an old OTA root from shadowing a fresh bundle.

final class OTAUpdater {
    static let shared = OTAUpdater()

    // Raw 32-byte ed25519 public key, base64. Counterpart of the OTA_SIGNING_KEY
    // deploy secret; generated by app/tools/ota-keygen.mjs. Rotating the key means
    // shipping a binary update with the new value here.
    private static let publicKeyB64 = "FJ3cdXKy8s/zSH83UtiEkF/Us5UYyiLN0rGhqngepGw="

    // Origin for the manifest AND content files. Debug/E2E builds may override via
    // `-OTABaseURL http://localhost:8788` launch arguments (UserDefaults).
    private var baseURL: URL {
        if let s = UserDefaults.standard.string(forKey: "OTABaseURL"), let u = URL(string: s) {
            return u
        }
        return URL(string: "https://disabilitywiki.org")!
    }

    // Refuse absurd deltas — a corrupt-but-signed manifest must not fill the disk.
    private let maxDeltaBytes = 300 * 1024 * 1024

    private let fm = FileManager.default

    private var contentDir: URL {
        let lib = fm.urls(for: .libraryDirectory, in: .userDomainMask)[0]
        return lib.appendingPathComponent("NoCloud/dw-content", isDirectory: true)
    }
    private var versionsDir: URL { contentDir.appendingPathComponent("versions", isDirectory: true) }
    private var currentPointer: URL { contentDir.appendingPathComponent("current") }
    private var previousPointer: URL { contentDir.appendingPathComponent("previous") }

    private var bundleRoot: URL? {
        Bundle.main.url(forResource: "public", withExtension: nil)
    }

    // MARK: - Serving root (called before the webview loads)

    /// The content root the webview should serve, or nil to use the app bundle.
    /// Cheap by design: pointer chase + structural validation + 3 hash spot-checks.
    func activeContentRoot() -> URL? {
        // New binary wins: bundle newer than OTA content → discard OTA state.
        if let bundleBuilt = builtAt(inRoot: bundleRoot),
           let otaRoot = pointedRoot(currentPointer),
           let otaBuilt = builtAt(inRoot: otaRoot),
           bundleBuilt > otaBuilt {
            try? fm.removeItem(at: contentDir)
            return nil
        }
        if let root = pointedRoot(currentPointer), validate(root: root) {
            return root
        }
        // Current is broken: roll back. Promote previous to current so the bad
        // root is never retried, and let staging start over from good state.
        if let prev = pointedRoot(previousPointer), validate(root: prev) {
            try? fm.removeItem(at: currentPointer)
            try? fm.moveItem(at: previousPointer, to: currentPointer)
            CAPLog.print("⚡️  OTA: current content failed validation — rolled back to previous")
            return prev
        }
        if fm.fileExists(atPath: contentDir.path) {
            try? fm.removeItem(at: contentDir)
            CAPLog.print("⚡️  OTA: content state invalid — reverted to app bundle")
        }
        return nil
    }

    private func pointedRoot(_ pointer: URL) -> URL? {
        guard let name = try? String(contentsOf: pointer, encoding: .utf8) else { return nil }
        let root = versionsDir.appendingPathComponent(name.trimmingCharacters(in: .whitespacesAndNewlines), isDirectory: true)
        var isDir: ObjCBool = false
        guard fm.fileExists(atPath: root.path, isDirectory: &isDir), isDir.boolValue else { return nil }
        return root
    }

    /// Structural + spot-hash validation of a content root. Full hashing happened
    /// at staging; this catches truncation/corruption without a launch-time cost.
    private func validate(root: URL) -> Bool {
        guard let manifest = try? loadManifest(at: root.appendingPathComponent("ota/manifest.json")) else { return false }
        // The reason this app exists: crisis pages must be present and intact.
        let probes = manifest.files.keys.filter { $0.hasPrefix("/crisis/") && $0.hasSuffix("/index.html") }.sorted().prefix(3)
        guard !probes.isEmpty else { return false }
        for path in probes {
            let f = root.appendingPathComponent(String(path.dropFirst()))
            guard let data = try? Data(contentsOf: f),
                  SHA256.hash(data: data).hexString == manifest.files[path]?.sha256 else { return false }
        }
        return fm.fileExists(atPath: root.appendingPathComponent("index.html").path)
    }

    private func builtAt(inRoot root: URL?) -> Date? {
        guard let root,
              let data = try? Data(contentsOf: root.appendingPathComponent("app-build.json")),
              let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let s = obj["builtAt"] as? String else { return nil }
        return ISO8601DateFormatter().date(from: s)
    }

    // MARK: - Update check (called after launch, off the main path)

    func checkForUpdateInBackground() {
        Task.detached(priority: .utility) { [self] in
            do { try await checkForUpdate() } catch {
                // Offline, refused signature, server hiccup — all fine: the app
                // keeps serving its last-known-good. Log and move on.
                CAPLog.print("⚡️  OTA: update check did not complete: \(error.localizedDescription)")
            }
        }
    }

    private func checkForUpdate() async throws {
        let session = URLSession(configuration: .ephemeral)

        // 1. Fetch manifest + signature; verify BEFORE parsing.
        let manifestBytes = try await fetch(session, baseURL.appendingPathComponent("ota/manifest.json"))
        let sigB64 = String(decoding: try await fetch(session, baseURL.appendingPathComponent("ota/manifest.sig")), as: UTF8.self)
        guard let sig = Data(base64Encoded: sigB64.trimmingCharacters(in: .whitespacesAndNewlines)),
              let pub = Data(base64Encoded: Self.publicKeyB64),
              let key = try? Curve25519.Signing.PublicKey(rawRepresentation: pub),
              key.isValidSignature(sig, for: manifestBytes) else {
            throw OTAError.badSignature
        }
        let manifest = try Self.decodeManifest(manifestBytes)

        // 2. Already current?
        let activeRoot = activeContentRoot() ?? bundleRoot
        guard let activeRoot else { throw OTAError.noContent }
        let activeManifest = try? loadManifest(at: activeRoot.appendingPathComponent("ota/manifest.json"))
        if let active = activeManifest, active.builtAt == manifest.builtAt { return }
        // Never move backwards: refuse a manifest older than what we serve
        // (a stale edge cache must not roll crisis content back).
        if let activeBuilt = activeManifest?.builtAtDate, let newBuilt = manifest.builtAtDate,
           newBuilt <= activeBuilt { return }

        // 3. Compute the delta and guard its size.
        var delta: [(path: String, entry: Manifest.Entry)] = []
        for (path, entry) in manifest.files where activeManifest?.files[path]?.sha256 != entry.sha256 {
            delta.append((path, entry))
        }
        let deltaBytes = delta.reduce(0) { $0 + $1.entry.size }
        guard deltaBytes <= maxDeltaBytes else { throw OTAError.deltaTooLarge(deltaBytes) }
        CAPLog.print("⚡️  OTA: update \(manifest.builtAt) — \(delta.count) files, \(deltaBytes / 1024) KB")

        // 4. Stage: hard-link unchanged files from the active root, download the rest.
        try? fm.removeItem(at: versionsDir.appendingPathComponent("staging"))
        let staging = versionsDir.appendingPathComponent("staging", isDirectory: true)
        try fm.createDirectory(at: staging, withIntermediateDirectories: true)
        var stagingValues = URLResourceValues()
        stagingValues.isExcludedFromBackup = true
        var stagingURL = contentDir
        try? stagingURL.setResourceValues(stagingValues)

        let changed = Set(delta.map(\.path))
        for (path, entry) in manifest.files {
            let dest = staging.appendingPathComponent(String(path.dropFirst()))
            try fm.createDirectory(at: dest.deletingLastPathComponent(), withIntermediateDirectories: true)
            if changed.contains(path) {
                let data = try await fetch(session, baseURL.appendingPathComponent(String(path.dropFirst())))
                guard SHA256.hash(data: data).hexString == entry.sha256 else { throw OTAError.fileHashMismatch(path) }
                try data.write(to: dest)
            } else {
                let src = activeRoot.appendingPathComponent(String(path.dropFirst()))
                do { try fm.linkItem(at: src, to: dest) } catch { try fm.copyItem(at: src, to: dest) }
            }
        }

        // 5. Carry the signed manifest into the root, and stamp it so the in-app
        //    freshness banner (and the new-binary check) reflect the OTA date.
        try fm.createDirectory(at: staging.appendingPathComponent("ota"), withIntermediateDirectories: true)
        try manifestBytes.write(to: staging.appendingPathComponent("ota/manifest.json"))
        try Data(sigB64.utf8).write(to: staging.appendingPathComponent("ota/manifest.sig"))
        let stamp = ["gitSha": manifest.gitSha ?? "", "builtAt": manifest.builtAt]
        try JSONSerialization.data(withJSONObject: stamp).write(to: staging.appendingPathComponent("app-build.json"))

        // 6. Activate atomically for the NEXT launch; keep one rollback root.
        let versionName = "v-" + manifest.builtAt.replacingOccurrences(of: ":", with: "-")
        let finalRoot = versionsDir.appendingPathComponent(versionName, isDirectory: true)
        try? fm.removeItem(at: finalRoot)
        try fm.moveItem(at: staging, to: finalRoot)
        guard validate(root: finalRoot) else {
            try? fm.removeItem(at: finalRoot)
            throw OTAError.stagedRootInvalid
        }
        let oldCurrent = try? String(contentsOf: currentPointer, encoding: .utf8)
        try? fm.removeItem(at: previousPointer)
        if let oldCurrent { try oldCurrent.write(to: previousPointer, atomically: true, encoding: .utf8) }
        try versionName.write(to: currentPointer, atomically: true, encoding: .utf8)

        // 7. Prune everything that is neither current nor previous.
        let keep: Set<String> = [versionName, oldCurrent?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""]
        for item in (try? fm.contentsOfDirectory(atPath: versionsDir.path)) ?? [] where !keep.contains(item) {
            try? fm.removeItem(at: versionsDir.appendingPathComponent(item))
        }
        CAPLog.print("⚡️  OTA: staged \(versionName); activates on next launch")
    }

    private func fetch(_ session: URLSession, _ url: URL) async throws -> Data {
        let (data, response) = try await session.data(from: url)
        guard let http = response as? HTTPURLResponse, http.statusCode == 200 else {
            throw OTAError.httpFailure(url.path)
        }
        return data
    }

    // MARK: - Manifest

    struct Manifest {
        struct Entry { let sha256: String; let size: Int }
        let gitSha: String?
        let builtAt: String
        let files: [String: Entry]
        var builtAtDate: Date? { ISO8601DateFormatter().date(from: builtAt) }
    }

    private func loadManifest(at url: URL) throws -> Manifest {
        try Self.decodeManifest(try Data(contentsOf: url))
    }

    private static func decodeManifest(_ data: Data) throws -> Manifest {
        guard let obj = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              obj["schema"] as? Int == 1,
              let builtAt = obj["builtAt"] as? String,
              let filesRaw = obj["files"] as? [String: [String: Any]] else {
            throw OTAError.badManifest
        }
        var files: [String: Manifest.Entry] = [:]
        files.reserveCapacity(filesRaw.count)
        for (path, e) in filesRaw {
            guard let sha = e["sha256"] as? String, let size = e["size"] as? Int else { throw OTAError.badManifest }
            files[path] = Manifest.Entry(sha256: sha, size: size)
        }
        return Manifest(gitSha: obj["gitSha"] as? String, builtAt: builtAt, files: files)
    }

    enum OTAError: LocalizedError {
        case badSignature, badManifest, noContent, stagedRootInvalid
        case fileHashMismatch(String), httpFailure(String), deltaTooLarge(Int)
        var errorDescription: String? {
            switch self {
            case .badSignature: return "manifest signature invalid or missing"
            case .badManifest: return "manifest malformed"
            case .noContent: return "no active content root"
            case .stagedRootInvalid: return "staged root failed validation"
            case .fileHashMismatch(let p): return "hash mismatch for \(p)"
            case .httpFailure(let p): return "HTTP failure fetching \(p)"
            case .deltaTooLarge(let n): return "delta too large (\(n) bytes)"
            }
        }
    }
}

private extension SHA256.Digest {
    var hexString: String { map { String(format: "%02x", $0) }.joined() }
}
